src/main/java/com/task/financer/domain/Notes.java
package com.task.financer.domain;

import javax.persistence.*;

@Entity
public class Notes {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String nameNotes;
    private String textNotes;


    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    private User author;

    public Notes() {
    }

    public Notes(String nameNotes, String textNotes, User user) {
        this.author = user;
        this.nameNotes = nameNotes;
        this.textNotes = textNotes;
    }


    public String getAuthorName() {
        return author != null ? author.getUsername() : "<none>";
    }

    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setNameNotes(String nameNotes) {
        this.nameNotes = nameNotes;
    }

    public void setTextNotes(String textNotes) {
        this.textNotes = textNotes;
    }

    public Long getId() {
        return id;
    }

    public String getNameNotes() {
        return nameNotes;
    }

    public String getTextNotes() {
        return textNotes;
    }
}

src/main/java/com/task/financer/domain/Role.java
package com.task.financer.domain;

import org.springframework.security.core.GrantedAuthority;

public enum Role implements GrantedAuthority {
    USER,
    ADMIN;

    @Override
    public String getAuthority() {
        return name();
    }
}

src/main/java/com/task/financer/domain/User.java
package com.task.financer.domain;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import javax.persistence.*;
import java.util.Collection;
import java.util.Set;

@Entity
@Table(name = "usr")
public class User implements UserDetails {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String username;
    private String fistName;
    private String lastName;
    private String password;
    private boolean active;


    @ElementCollection(targetClass = Role.class, fetch = FetchType.EAGER)
    @CollectionTable(name = "user_role", joinColumns = @JoinColumn(name = "user_id"))
    @Enumerated(EnumType.STRING)
    private Set<Role> roles;

    @OneToMany(mappedBy = "author", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private Set<Notes> notes;

    public Set<Notes> getNotes() {
        return notes;
    }

    public void setNotes(Set<Notes> notes) {
        this.notes = notes;
    }

    public String getFistName() {
        return fistName;
    }

    public void setFistName(String fistName) {
        this.fistName = fistName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return isActive();
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return getRoles();
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public Set<Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }
}

src/main/java/com/task/financer/controller/MainController.java
package com.task.financer.controller;


import com.task.financer.domain.User;
import com.task.financer.repos.NotesRepo;
import com.task.financer.repos.UserRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Map;

@Controller
/*@RequestMapping(path = "/") // This means URL's start with /demo (after Application path)*/
public class MainController {
    @Autowired
    private UserRepo userRepo;
    @Autowired
    private NotesRepo notesRepo;

    @GetMapping("/")
    public String greeting(Map<String, Object> model) {
        return "greeting";
    }

    @GetMapping("/main")
    public String main(Map<String, Object> model) {
        model.put("some", "hello, azazka!");
        return "greeting";
    }


    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepo.findAll();
    }

}

src/main/java/com/task/financer/controller/NoteController.java
package com.task.financer.controller;

import com.task.financer.domain.Notes;
import com.task.financer.domain.User;
import com.task.financer.repos.NotesRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.ArrayList;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

@Controller
public class NoteController {

    @Autowired
    private NotesRepo notesRepo;


    @GetMapping("/note")
    public String noteMain(Model model) {
        Iterable<Notes> notes = notesRepo.findAll();
        model.addAttribute("notes", notes);
        return "notes-user";
    }

    @PostMapping("/note/add")
    public String notePostAdd(
            @AuthenticationPrincipal User user,
            @RequestParam String title,
            @RequestParam String note, Map<String, Object> model
    ) {
        Notes notes = new Notes(title, note, user);
        notesRepo.save(notes);
        Iterable<Notes> notess = notesRepo.findAll();
        model.put("messages", notess);

        return "redirect:/note";
    }

    @GetMapping("/note/{id}/edit")
    public String noteEdit(@PathVariable(value = "id") long noteId, Model model) {
        Optional<Notes> note = notesRepo.findById(noteId);
        ArrayList<Notes> res = new ArrayList<>();
        note.ifPresent(res::add);
        model.addAttribute("notes", res);
        return "notesEdit";
    }

    @PostMapping("/note/{id}/edit")
    public String noteUpdate(@PathVariable(value = "id") long noteId,
                             @RequestParam String title,
                             @RequestParam String note, Model model) {
        Notes notes = notesRepo.findById(noteId).orElseThrow();
        notes.setNameNotes(title);
        notes.setTextNotes(note);
        notesRepo.save(notes);
        return "redirect:/note";
    }

    @GetMapping("/note/{id}")
    public String noteDetails(@PathVariable(value = "id") long noteId, Model model) {
        if (!notesRepo.existsById(noteId)) {
            return "redirect:/note";
        }
        Optional<Notes> note = notesRepo.findById(noteId);
        ArrayList<Notes> res = new ArrayList<>();
        note.ifPresent(res::add);
        model.addAttribute("notes", res);
        return "notes-details";
    }

    @GetMapping("/user-notes/{user}")
    public String userNotes(
            @AuthenticationPrincipal User currentUser,
            @PathVariable User user, Model model,
            @RequestParam(required = false) Notes notes
    ) {
        Set<Notes> note = user.getNotes();

        model.addAttribute("notes", notes);
        model.addAttribute("note", note);
        model.addAttribute("isCurrentUser", currentUser.equals(user));

        return "notes-details";
    }

    @GetMapping("/delete/{id}")
    public String delete(@PathVariable(value = "id") long noteId, Model model) {
        Notes notes = notesRepo.findById(noteId).orElseThrow();
        notesRepo.delete(notes);
        return "redirect:/note";
    }
}

src/main/java/com/task/financer/controller/RegistrationController.java
package com.task.financer.controller;


import com.task.financer.domain.User;
import com.task.financer.service.UserSevice;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;

import java.util.Map;

@Controller
public class RegistrationController {
    @Autowired
    private UserSevice userSevice;

    @GetMapping("/registration")
    public String registration() {
        return ("/registration");
    }

    @PostMapping("/registration")
    public String addUser(User user, Map<String, Object> model) {
        if (!userSevice.addUser(user)) {
            model.put("message", "User exists!");
            return "registration";
        }
        return "redirect:/login";
    }
}

src/main/java/com/task/financer/controller/UserController.java
package com.task.financer.controller;


import com.task.financer.domain.Role;
import com.task.financer.domain.User;
import com.task.financer.service.UserSevice;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@Controller
@RequestMapping("/user")

public class UserController {
    @Autowired
    private UserSevice userSevice;

    @GetMapping
    public String userList(Model model) {
        model.addAttribute("users", userSevice.findAll());

        return "userList";
    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @GetMapping("{user}")
    public String userEditForm(@PathVariable User user, Model model) {
        model.addAttribute("user", user);
        model.addAttribute("roles", Role.values());

        return "userEdit";
    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @PostMapping
    public String userSave(
            @RequestParam String username,
            @RequestParam Map<String, String> form,
            @RequestParam("userId") User user
    ) {
        userSevice.saveUser(user, username, form);

        return "redirect:/user";
    }

    @GetMapping("profile")
    public String getProfile(Model model,
                             @AuthenticationPrincipal User user) {
        model.addAttribute("username", user.getUsername());
        model.addAttribute("fistName", user.getFistName());
        model.addAttribute("lastName", user.getLastName());

        return "profile";
    }

    @PostMapping("profile")
    public String updateProfile(
            @AuthenticationPrincipal User user,
            @RequestParam String password,
            @RequestParam String fistName,
            @RequestParam String lastName) {
        userSevice.updateProfile(user, password, fistName, lastName);
        return "redirect:/user/profile";
    }

    @GetMapping("user/delete/{id}")
    public String deleteUser(@PathVariable User id) {
        userSevice.deleteUser(id);
        return "redirect:/user";

    }
}

src/main/resources/templates/greeting.ftl
<#import "parts/common.ftl" as common>
<#include "parts/security.ftl">

<@common.page>
    <style>
        body {
            background-image: url(https://clipart-db.ru/file_content/rastr/background_065.jpg);
            background-color: #000000;
        }
    </style>
    <h6 class="display-3"> Hello ${name} Please login </h6>

</@common.page>

src/main/resources/templates/login.ftl
<#import "parts/common.ftl" as c>
<#import "parts/login.ftl" as l>

<@c.page>
    ${message?ifExists}
    <@l.login "/login" false/>
</@c.page>

src/main/resources/templates/main.ftl
<#import "parts/common.ftl" as c>


<title>Главная</title>
<@c.page>
    <h1 class="cover-heading">Cover your page.</h1>
</@c.page>

src/main/resources/templates/notes-details.ftl
<#import "parts/common.ftl" as c>
<#import "parts/login.ftl" as l>
<#import "parts/note-form.ftl" as n>

<@c.page>
<table class="table table-bordered table-hover horizontal-align">
    <thead>
    <tr>
        <th style="width: 5%">ID</th>
        <th>Note Name</th>
        <th style="width: 60%">Message</th>
        <th style="width: 60%">Author</th>
        <th style="width: 5%">Edit</th>
        <th style="width: 5%">Delete</th>
    </tr>

    </thead>



    <tbody>

    <#list note as note>
    <tr>
        <td> ${note.id}</td>
        <td> ${note.nameNotes} </td>
        <td>${note.textNotes}</td>
        <td>${note.authorName}</td>

        <td><a href="/note/${note.id}/edit"><i class="fa fa-pencil-square-o" style="font-size:20px"></i> Edit </a></td>
        <td><a href="/delete/${note.id}"><i class="fa fa-trash" style="font-size:20px"></i> Delete </a></td>
    </tbody>

    <#else>
        <div class="alert  alert-primary" role="alert" style="width: 200px" >
            No message.
        </div>
    </#list>

    </@c.page>

src/main/resources/templates/notes-user.ftl
<#import "parts/common.ftl" as c>
<#import "parts/login.ftl" as l>
<#import "parts/note-form.ftl" as n>

<@c.page>
    <table class="table table-bordered table-hover horizontal-align">
    <thead>
    <tr>
        <th style="width: 5%">ID</th>
        <th>Note Name</th>
        <th style="width: 60%">Message</th>
        <th style="width: 60%">Author</th>
        <th style="width: 5%">Edit</th>
        <th style="width: 5%">Delete</th>
    </tr>
    </thead>
    <tbody>

    <#list notes as note>
        <tr>
            <td> ${note.id}</td>
            <td> ${note.nameNotes} </td>
            <td>${note.textNotes}</td>
            <td>${note.authorName}</td>

            <td><a href="/note/${note.id}/edit"><i class="fa fa-pencil-square-o" style="font-size:20px"></i> Edit </a>
            </td>
            <td><a href="/delete/${note.id}"><i class="fa fa-trash" style="font-size:20px"></i> Delete </a></td>
        </tbody>
    <#else>
        <div class="alert  alert-primary" role="alert" style="width: 200px" >
            No message.
        </div>
    </#list>

</@c.page>
<@n.notes>

</@n.notes>

src/main/resources/templates/notesEdit.ftl
<#import "parts/common.ftl" as c>
<#import "parts/login.ftl" as l>
<#import "parts/note-form.ftl" as n>

<@c.page>
    <table class="table table-bordered table-hover horizontal-align">

    <thead>
    <tr>
        <th style="width: 5%">ID</th>
        <th>Note Name</th>
        <th style="width: 60%">Text Message</th>
        <th style="width: 5%">Edit</th>
    </tr>
    </thead>

    <tbody>
    <div class="container mt-5 mb-5"></div>

    <h1>Редактор заметок</h1>
<form action="/note/${id}/edit" method="post">
    <#list notes as note>
    <tr>
        <td> ${note.id}</td>
        <td><input type="text" name="title" placeholder="${note.nameNotes}"></td>
        <td><input type="text" name="note" placeholder="${note.textNotes}"></td>
        <input type="hidden" name="_csrf" value="${_csrf.token}"/>
        <td><label><input type="submit" class="btn btn-success" value="Обновить"></label><br></td>
</form>
    </tbody>
</#list>
</@c.page>

src/main/resources/templates/profile.ftl
<#import "parts/common.ftl" as c>


<@c.page>

<form method="post">
    <div class="text-center">
        <a class="user-avatar user-avatar-xl"><img src="assets/images/avatars/profile.jpg" alt=""></a>
        <h2 class="h4 mt-2 mb-0"> ${fistName! ''} ${lastName! ''} </h2>
        <div class="my-1">
            <i class="fa fa-star has-text-black"></i>
            <i class="fa fa-star text-yellow"></i>
            <i class="fa fa-star text-yellow"></i>
            <i class="fa fa-star text-yellow"></i>
            <i class="fa fa-star text-yellow"></i>
        </div>
        <p class="text-muted"> Info about user </p>
        <p> Skills user </p>
    </div>

    <div class="col-lg-8-fluid">
        <div class="card card-fluid">
            <h6 class="card-header"> Account </h6>
            <div class="card-body">
                <form method="post">
                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            <label for="input01">First Name</label> <input type="text" name="fistName" class="form-control" id="input01" value="${fistName! ''}" required="">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="input02">Last Name</label> <input type="text" name="lastName" class="form-control" id="input02" value="${lastName! ''}" required="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input03">Email</label> <input type="email" class="form-control" id="input03" value="bent10@looper.com" required="">
                    </div>
                    <div class="form-group">
                        <label for="input04">New Password</label> <input type="password" name="password" value="secret" class="form-control" id="input04" required="">
                    </div>
                    <div class="form-group">
                        <label for="input05">Username</label> <input type="text" class="form-control" id="input05" value="${username}" required="">
                    </div>
                    <hr>
                    <div class="form-actions mb-3">
                        <input type="hidden" name="_csrf" value="${_csrf.token}"/>
                        <input type="password" class="form-control mr-3" id="input06" placeholder="Enter Current Password" required="">
                    </div>
                    <button type="submit" class="btn btn-primary text-nowrap ml-auto" >Update Account</button>
                </form>
            </div>
        </div>
    </div>
</@c.page>

src/main/resources/templates/registration.ftl
<#import "parts/common.ftl" as c>
<#import "parts/login.ftl" as l>

<@c.page>
    <div class="mb-1">Add new user</div>
    ${message?ifExists}
    <@l.login "/registration" true />
</@c.page>

src/main/resources/templates/userEdit.ftl
<#import "parts/common.ftl" as c>

<@c.page>
User editor

<form action="/user" method="post">
    <input type="text" name="username" value="${user.username}">
    <#list roles as role>
    <div>
        <label><input type="checkbox" name="${role}" ${user.roles?seq_contains(role)?string("checked", "")}>${role}</label>
    </div>
    </#list>
    <input type="hidden" value="${user.id}" name="userId">
    <input type="hidden" value="${_csrf.token}" name="_csrf">
    <button type="submit">Save</button>
</form>
</@c.page>

src/main/resources/templates/userList.ftl
<#import "parts/common.ftl" as common>
<@common.page>
List of users
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Role</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <#list users as user>
        <tr>
            <td>${user.username}</td>
            <td><#list user.roles as role>${role}<#sep>, </#list></td>
            <td><a href="/user/${user.id}">edit</a></td>
            <td><a href="/user/user/delete/${user.id}">delete</a></td>

        </tr>
    </#list>
    </tbody>
</table>
</@common.page>